### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by jacklmbrt07** [jacklmbrt07/merge-immersive#19]
Signup function is working
Logout function is working
Login is not working.

It was working Friday however, and we have not found any spelling/syntax issues. 
brings up alert "Invalid Credentials!!!" 
and terminal says `POST /api/users/signup 400 1.143 ms - 301`

we cannot find the bug

![image](https://user-images.githubusercontent.com/61360118/91074891-1081a680-e5f2-11ea-8a52-9d5ce468d7dd.png)

Also, went through the lecture notes:
https://sei-r-629.netlify.app/react-fundamentals/week-2/day-4/lecture-materials/token-based-auth-with-react-and-jwts

**Comment by myDeveloperJourney** [comment]
@jacklmbrt07 @Johnathanblackburncodes @HoseaCodes 

That was a fun debug session guys! So this is what we did to fix this issue. 💪 

Steps that were taken to debug the issue:

- Finding the login controller action and console logging the error object but the request never seemed to make it to the backend - the point of failure seemed

- Then we went to the login component and console logged the `error` 
object, so the first issue seemed to come from the `userService`. The login Utility function was missing the call the fetch API

- Then we reattempted login and got another error that indicated that `this.props.handleSignUpOrLogin` was not a function, so we checked what we were referencing and it turned out we had a spelling error

- Once corrected we learned that we had another error that was created whenever we attempted to push into the history stack. The error message said that `this.props.history.push` was not a function. So we were able to solve this issue by going to `App.js` and spreading the props object from the React Route component to the `LoginPage` component

- Once corrected this issue, we were able to successfully login!


I won't be able to close this issue since I'm not a contributor, but I highly suggest closing this once you have a chance
